DROP TABLE XX_GENERIC_LABELS ;

DROP TABLE XX_GENERIC_LABELS_TEMP ;

DROP TABLE USERS ;

DROP TABLE ROLE;

--DROP TABLE PRODUCT

DROP SEQUENCE GENERIC_SEQ ;

CREATE TABLE XX_GENERIC_LABELS (PRINT_LABEL_GROUP_NBR NUMBER, FACILITY_ID VARCHAR2(3), CONTAINER_ID VARCHAR2(20) );

CREATE TABLE XX_GENERIC_LABELS_TEMP (PRINT_LABEL_GROUP_NBR NUMBER, FACILITY_ID VARCHAR2(3), CONTAINER_ID VARCHAR2(20) );


 CREATE TABLE USERS 
   (	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA"  ENABLE, 
	 CONSTRAINT "UK_RANY37860R76XEH1BNGB1G4N9" UNIQUE ("USER_NAME", "PASSWORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA" ;
  
  
  
  CREATE TABLE ROLE
   (	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA"  ENABLE, 
	 CONSTRAINT "UK_IFYV8OM78CGY2A9NROXOY517Y" UNIQUE ("USER_ID", "ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA"  ENABLE, 
	 CONSTRAINT "FK_KYICCJHFFIRJI07HQFRSGTOIG" FOREIGN KEY ("USER_ID")
	  REFERENCES "RWMS15DEV"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA" ;
  
INSERT INTO users (user_id, first_name, last_name, email, user_name, password, enabled) VALUES
(1, 'Kate', 'Morton', 'kate123@gmail.com', 'kate', '$2a$10$niwmCfG7XiV455YZ1550je7qmQ/AjyYc1McxAcr8LRsUBlJzUwWB6', 1);

INSERT INTO users (user_id, first_name, last_name, email, user_name, password, enabled) VALUES
(2, 'Alex', 'Perry', 'alex123@yahoo.com', 'alex', '$2a$10$nka18qu7p/uaZd82BV32auRs2Pdi7Cx1rstd08JGuuKp535XfIa1y', 1);

INSERT INTO role (role_id, user_id, role) VALUES
(1, 1, 'ROLE_ADMIN');

INSERT INTO role (role_id, user_id, role) VALUES
(2, 2, 'ROLE_USER');

 CREATE TABLE "RWMS15DEV"."PRODUCT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER(19,0) NOT NULL ENABLE, 
	"QTY" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA" ;


ALTER TABLE PRODUCT_TEMP
  ADD barcode varchar2(45); 

ALTER TABLE PRODUCT
  ADD barcode varchar2(45); 


CREATE SEQUENCE GENERIC_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER 
GENERIC_UPLOAD_TRIG 
AFTER
  INSERT
    ON CONT_LABELS_TO_PRINT FOR EACH ROW 
    DECLARE 
    V_ID NUMBER;
    V_CONTAINER_ID CONTAINER.CONTAINER_ID%TYPE;
  BEGIN
      
      IF :NEW.LABEL_TYPE='GENERIC' THEN
        INSERT
        INTO
          XX_GENERIC_LABELS
          (
            PRINT_LABEL_GROUP_NBR,
            FACILITY_ID,
            CONTAINER_ID 
          )
          VALUES
          (
           :NEW.PRINT_LABEL_GROUP_NBR,
            :NEW.FACILITY_ID,
            :NEW.CONTAINER_ID
          );
        END IF;
  END;
  /
  
  
  CREATE OR REPLACE TRIGGER 
GENERIC_TEMP_UPLOAD_TRIG 
AFTER
  INSERT
    ON XX_GENERIC_LABELS FOR EACH ROW 
    DECLARE 
  BEGIN
      
        INSERT
        INTO
          XX_GENERIC_LABELS_TEMP
          (
            PRINT_LABEL_GROUP_NBR,
            FACILITY_ID,
            CONTAINER_ID 
          )
          VALUES
          (
            :NEW.PRINT_LABEL_GROUP_NBR,
            :NEW.FACILITY_ID,
            :NEW.CONTAINER_ID
          );
  END;
  /
